# Generated by Django 6.0.3 on 2026-03-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatedtask',
            name='backend_task_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
