# Generated by Django 6.0.3 on 2026-06-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example_app", "0002_democontentstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="status",
            field=models.CharField(
                choices=[("backlog", "Grazing"), ("active", "Galloping"), ("done", "Show Ready")],
                default="backlog",
                max_length=20,
            ),
        ),
    ]
